// src/renderer/pages/chatLayout/Layout.tsx
import { useState } from 'react';
import ChatAside from './ChatAside';
import MenuDividerArrow from './MenuDividerArrow';
import ChatMain from './ChatMain';
import ChatSideBar from './ChatSideBar';

function Layout() {
  const [hideLeft, setHideLeft] = useState(false);
  const [hideRight, setHideRight] = useState(true);

  function hideMenuHandler() {
    setHideLeft(!hideLeft);
  }

  function hideSideBarHandler() {
    const myDrawer = document.getElementById('my-drawer-4');
    myDrawer?.click();
    setHideRight(!hideRight);
  }

  return (
    <div className="flex h-full flex-row justify-start">
      {!hideLeft ? <ChatAside /> : null}
      {hideLeft ? null : null}
      <div
        role="button"
        tabIndex={0}
        className="flex flex-col justify-center"
        onClick={() => hideMenuHandler()}
        onKeyDown={() => {}}
      >
        <div>{MenuDividerArrow({ rotate: !hideLeft })}</div>
      </div>
      <ChatMain />
      <div
        role="button"
        tabIndex={0}
        className="fixed right-2.5 top-1/2"
        onClick={() => hideSideBarHandler()}
        onKeyDown={() => {}}
      >
        {MenuDividerArrow({ initRotate: true })}
      </div>
      {ChatSideBar(hideRight, (h) => setHideRight(h))}
    </div>
  );
}

export default Layout;

// src/renderer/pages/chatLayout/Layout.vue
<template>
	<div class="flex h-full flex-row justify-start">
		<chat-aside @changePlugin="changePluginHandler" v-if="!hide" class="hover:bg-base-300"></chat-aside>
		<MenuDividerArrow :rotate="!hide" @click="hideMenuHandler"></MenuDividerArrow>
    <ChatMain ref="chatMain" class="w-full"></ChatMain>
		<MenuDividerArrow :init-rotate="true" @click="hideSideBarHandler" class="fixed right-2.5 top-1/2"></MenuDividerArrow>
		<chat-side-bar></chat-side-bar>
	</div>
</template>

<script setup lang="ts">
import { onMounted, ref, defineAsyncComponent } from 'vue'
import { ipcRenderer } from 'electron'
import ChatAside from './ChatAside.vue'

const ChatSideBar = defineAsyncComponent(() => import('./ChatSideBar.vue'))

const MenuDividerArrow = defineAsyncComponent(() => import('../../components/MenuDividerArrow.vue'))
const ChatMain = defineAsyncComponent(() => import('./ChatMain.vue'))

onMounted(() => {
	ipcRenderer.on('hideMenu', () => {
		hide.value = true
	})
})

// sidebar menu
const hide = ref(false)

function hideMenuHandler() {
	hide.value = !hide.value
}
function hideSideBarHandler() {
	let myDrawer = document.getElementById('my-drawer-4')
	myDrawer?.click()
}

const chatMain = ref()
function changePluginHandler(isClearContext: boolean) {
  chatMain.value.changePluginHandler(isClearContext)
}
</script>

<style scoped></style>
