// src/renderer/components/MenuDividerArrow.vue
<script setup lang="ts">
import { defineAsyncComponent, ref, toRef } from "vue";

const props = defineProps(['rotate', 'initRotate'])
let hide = toRef(props, 'rotate')
let initRotate = toRef(props, 'initRotate')

const DoubleArrowSVG = defineAsyncComponent(() =>
  import("./DoubleArrowSVG.vue"),
);
</script>

<template>
  <div class="flex flex-col justify-center cursor-pointer">
    <div :class="!hide ? 'rotate-180' : 'rotate-0'">
      <DoubleArrowSVG :width="17" :height="17" :class="initRotate ? 'rotate-180' : ''"></DoubleArrowSVG>
    </div>
  </div>
</template>

<style scoped>

</style>

// src/renderer/pages/chatLayout/MenuDividerArrow.tsx
import React from 'react';
// import PropTypes from 'prop-types';
import DoubleArrowSVG from '../svg/DoubleArrowSVG';

type MyComponentProps = {
  rotate?: boolean;
  initRotate?: boolean;
};

function MenuDividerArrow({ rotate, initRotate }: MyComponentProps) {
  return (
    <div className="flex flex-col justify-center cursor-pointer">
      <div className={!rotate ? 'rotate-180' : 'rotate-0'}>
        <div className={initRotate ? 'rotate-180' : ''}>
          {DoubleArrowSVG('17', '17')}
        </div>
      </div>
    </div>
  );
}

// MenuDividerArrow.propTypes = {
//   rotate: PropTypes.bool,
//   initRotate: PropTypes.bool,
// };

MenuDividerArrow.defaultProps = {
  rotate: false,
  initRotate: false,
};

export default MenuDividerArrow;
